Traceback (most recent call last):
  File "C:\Users\USER\miniconda3\envs\ml_tf\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\USER\miniconda3\envs\ml_tf\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\USER\miniconda3\envs\ml_tf\lib\site-packages\jupyter_core\utils\__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
  File "C:\Users\USER\miniconda3\envs\ml_tf\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\USER\miniconda3\envs\ml_tf\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\Users\USER\miniconda3\envs\ml_tf\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\USER\miniconda3\envs\ml_tf\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import seaborn as sns
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[1], line 1[0m
[1;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mseaborn[39;00m [38;5;28;01mas[39;00m [38;5;21;01msns[39;00m

File [1;32m~\miniconda3\envs\ml_tf\lib\site-packages\seaborn\__init__.py:2[0m
[0;32m      1[0m [38;5;66;03m# Import seaborn objects[39;00m
[1;32m----> 2[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mrcmod[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m  [38;5;66;03m# noqa: F401,F403[39;00m
[0;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mutils[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m  [38;5;66;03m# noqa: F401,F403[39;00m
[0;32m      4[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mpalettes[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m  [38;5;66;03m# noqa: F401,F403[39;00m

File [1;32m~\miniconda3\envs\ml_tf\lib\site-packages\seaborn\rcmod.py:3[0m
[0;32m      1[0m [38;5;124;03m"""Control plot style and scaling using the matplotlib rcParams interface."""[39;00m
[0;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mfunctools[39;00m
[1;32m----> 3[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m [38;5;28;01mas[39;00m [38;5;21;01mmpl[39;00m
[0;32m      4[0m [38;5;28;01mfrom[39;00m [38;5;21;01mcycler[39;00m [38;5;28;01mimport[39;00m cycler
[0;32m      5[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m [38;5;28;01mimport[39;00m palettes

File [1;32m~\miniconda3\envs\ml_tf\lib\site-packages\matplotlib\__init__.py:153[0m
[0;32m    150[0m [38;5;28;01mimport[39;00m [38;5;21;01mtempfile[39;00m
[0;32m    151[0m [38;5;28;01mimport[39;00m [38;5;21;01mwarnings[39;00m
[1;32m--> 153[0m [38;5;28;01mimport[39;00m [38;5;21;01mnumpy[39;00m
[0;32m    154[0m [38;5;28;01mfrom[39;00m [38;5;21;01mpackaging[39;00m[38;5;21;01m.[39;00m[38;5;21;01mversion[39;00m [38;5;28;01mimport[39;00m parse [38;5;28;01mas[39;00m parse_version
[0;32m    156[0m [38;5;66;03m# cbook must import matplotlib only within function[39;00m
[0;32m    157[0m [38;5;66;03m# definitions, so it is safe to import from it here.[39;00m

File [1;32m~\miniconda3\envs\ml_tf\lib\site-packages\numpy\__init__.py:134[0m
[0;32m    131[0m [38;5;28;01mimport[39;00m [38;5;21;01msys[39;00m
[0;32m    132[0m [38;5;28;01mimport[39;00m [38;5;21;01mwarnings[39;00m
[1;32m--> 134[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01m_globals[39;00m [38;5;28;01mimport[39;00m _NoValue, _CopyMode
[0;32m    135[0m [38;5;66;03m# These exceptions were moved in 1.25 and are hidden from __dir__()[39;00m
[0;32m    136[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01mexceptions[39;00m [38;5;28;01mimport[39;00m (
[0;32m    137[0m     ComplexWarning, ModuleDeprecationWarning, VisibleDeprecationWarning,
[0;32m    138[0m     TooHardError, AxisError)

File [1;32m~\miniconda3\envs\ml_tf\lib\site-packages\numpy\_globals.py:20[0m
[0;32m      1[0m [38;5;124;03m"""[39;00m
[0;32m      2[0m [38;5;124;03mModule defining global singleton classes.[39;00m
[0;32m      3[0m 
[1;32m   (...)[0m
[0;32m     16[0m 
[0;32m     17[0m [38;5;124;03m"""[39;00m
[0;32m     18[0m [38;5;28;01mimport[39;00m [38;5;21;01menum[39;00m
[1;32m---> 20[0m [38;5;28;01mfrom[39;00m [38;5;21;01m.[39;00m[38;5;21;01m_utils[39;00m [38;5;28;01mimport[39;00m set_module [38;5;28;01mas[39;00m _set_module
[0;32m     22[0m __all__ [38;5;241m=[39m [[38;5;124m'[39m[38;5;124m_NoValue[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124m_CopyMode[39m[38;5;124m'[39m]
[0;32m     25[0m [38;5;66;03m# Disallow reloading this module so as to preserve the identities of the[39;00m
[0;32m     26[0m [38;5;66;03m# classes defined here.[39;00m

[1;31mModuleNotFoundError[0m: No module named 'numpy._utils'

